services:
  - type: web
    name: fitness-tracker-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn fitness_tracker.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: fitness-tracker-db
          property: connectionString

databases:
  - name: fitness-tracker-db
    plan: free
